### ISSUE TITLE
Vulture

### ISSUE THREAD

**Issue by MJGGerdes** [raoulg/MADS-DAV#4]
Afgelopen dinsdag zei je dat je Vulture had toegevoegd zodat we onze code konden laten controleren.
Ik zie die niet terugkomen in de toml file.
Waar kan ik dit vinden?

Ik zie alleen dit:
lint = [
    "black>=23.12.1",
    "isort>=5.13.2",
    "ruff>=0.1.14",
    "mypy>=1.8.0",
]

**Comment by raoulg** [comment]
Ah, ja, nee, dat heb ik niet toegevoegd aan de dependencies van de repo. Ik heb zelf een script, waarmee ik jullie code test, en daar heb ik ook vulture aan toegevoegd. De output daarvan zit in error.txt die ik in jouw repo push
